//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.02 at 02:54:28 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ezgiozkaya/subscriber", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ezgiozkaya.subscriber;
